version: 0.2
env:
  variables:
    APP_NAME: "<<APP_NAME>>"
  parameter-store:
      ###############################################################
      #          INTEGRATE FORTIFY ON DEMAND                        #
        FOD_RELEASE_ID: "/fod/releaseid"
        FOD_TENANT: "/fod/tenant"
        FOD_USER: "/fod/user"
        FOD_PAT: "/fod/pat"  
      ###############################################################
      #           INTEGRATE FORTIFY SCANCENTRAL                     #
        FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: "/fortify/client_auth_token"
        FCLI_DEFAULT_SSC_USER: "/fortify/ssc_user"
        FCLI_DEFAULT_SSC_PASSWORD: "/fortify/ssc_password"
        FCLI_DEFAULT_SSC_CI_TOKEN: "/fortify/ci_token"
        FCLI_DEFAULT_SSC_URL: "/fortify/ssc_url"
        SSC_APP_VERSION_ID: "/fortify/ssc_app_versionid"
phases:
  install:
    runtime-versions:
      dotnet: 3.1
  pre_build:
    commands:
      - dotnet restore AspNetCoreWebApplication/aspnet-core-dotnet-core.csproj
  build:
    commands:
      - dotnet publish -c release -o ./build_output AspNetCoreWebApplication/aspnet-core-dotnet-core.csproj
#      - dotnet vstest AspNetCoreWebApplicationTest/bin/release/netcoreapp3.1/AspNetCoreWebApplicationTest.dll
  post_build:
    commands:
      # Do not remove this statement. This command is required for AWS CodeBuild projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN in template-configuration.json file so AWS CloudFormation can tag project resources.
      - sed -i.bak 's/\$PARTITION\$/'${PARTITION}'/g;s/\$AWS_REGION\$/'${AWS_REGION}'/g;s/\$ACCOUNT_ID\$/'${ACCOUNT_ID}'/g;s/\$PROJECT_ID\$/'${PROJECT_ID}'/g' template-configuration.json
      ###################################################
      #             INTEGRATE FORTIFY SAST              #
      #                                                 #
      # For FORTIFY ON DEMAND uncomment the next line   #
      - bash fortify_sast_fod_template.bash
      #                                                 #
      # For FORTIFY SCANCENTRAL uncomment the next line #
      #- bash fortify_sast_scancentral_template.bash
      #                                                 #
      #                                                 #
      ###################################################
artifacts:
  files:
    - template.yml
    - AspNetCoreWebApplication/**/*
    - scripts/**/*
    - appspec.yml
    - requirements.txt
    - template-configuration.json
