version: 0.2
env:
  shell: bash
  secret-manager:
        FoDPAT: ${Secrets}:FoDPAT
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  pre_build:
    commands:
      #- mvn clean compile test
      - echo "Entered the install phase..."
  build:
    commands:
      - echo "Entered the build phase..."
      - Region = ${AWS_REGION}
      - Account_Id = $(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')
      - docker run --rm -v $PWD:/data fortifydocker/fortify-ci-tools:latest-jdk-17 sh -c "cd /data && scancentral package -bt mvn -o package.zip -oss"
      - docker run --rm -v $PWD:/data fortifydocker/fortify-ci-tools:latest-jdk-17 sh -c "cd /data && export FCLI_DEFAULT_FOD_URL=$FOD_URL && export FCLI_DEFAULT_FOD_USER=$FOD_USER && export FCLI_DEFAULT_FOD_PASSWORD=$FOD_PAT && export FCLI_DEFAULT_FOD_TENANT=$FOD_TENANT && fcli fod session login && fcli fod sast start --release=$FOD_RELEASE_ID --file=package.zip --remediation=NonRemediationScanOnly && fcli fod session logout"
      - docker run --rm -u $(id -u):$(id -g) -v $PWD:/data -e FCLI_DEFAULT_FOD_URL -e FCLI_DEFAULT_FOD_USER -e FCLI_DEFAULT_FOD_PASSWORD -e FCLI_DEFAULT_FOD_TENANT fortifydocker/fcli:2.7.0 fcli fod session login
      - docker run --rm -u $(id -u):$(id -g) -v $PWD:/data fortifydocker/fcli:2.7.0 fcli fod action run aws-sast-report --release=$FOD_RELEASE_ID --aws-region=$Region --aws-account=$Account_Id
      - aws lambda invoke --function-name=fortify-aws-security-hub-parser --payload=file://aws-fortify-report.json --cli-binary-format raw-in-base64-out fortify_scan_report.json
