# Integrate Fortify ScanCentral Static AppSec Testing (SAST) into your Google Cloud Build pipeline
# The following Google Cloud Build Secrets must be defined before using this step
# ******* FOR SCANCENTRAL ************
#   - $$FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN
#   - $$FCLI_DEFAULT_SSC_USER
#   - $$FCLI_DEFAULT_SSC_PASSWORD
#   - $$FCLI_DEFAULT_SSC_CI_TOKEN
#   - $$FCLI_DEFAULT_SSC_URL
#   - $$SSC_APP_VERSION_ID
# ******* FOR FOD ************
#   - $$FOD_RELEASE_ID
#   - $$FOD_USER
#   - $$FOD_PAT
#   - $$FOD_TENANT
steps:
- name: 'python:3.9'
  args: ['python', '-m', 'pip', 'install', '-r', 'requirements.txt', '--user']
  
- name: 'python'
  ###################################################
  #             INTEGRATE FORTIFY SAST              #
  #                                                 #
  # For FORTIFY ON DEMAND uncomment the next line   #
  #args: ['bash', './fortify_sast_fod_template.bash']
  #                                                 #
  # For FORTIFY SCANCENTRAL uncomment the next line #
  #args: ['bash', './fortify_sast_scancentral_template.bash']
  #                                                 #
  ###################################################
  args: ['bash', './fortify_sast_fod_template.bash']
  secretEnv: ['FOD_RELEASE_ID', 'FOD_USER', 'FOD_PAT', 'FOD_TENANT', 'FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN', 'FCLI_DEFAULT_SSC_USER', 'FCLI_DEFAULT_SSC_PASSWORD', 'FCLI_DEFAULT_SSC_CI_TOKEN', 'FCLI_DEFAULT_SSC_URL'] 
  env:
    - 'SSC_APP_VERSION_ID=${_SSC_APP_VERSION_ID}'
    - 'SC_SAST_SENSOR_VERSION=22.2'  
    - 'FOD_URL=https://ams.fortify.com' 
    - 'FOD_API_URL=https://api.ams.fortify.com' 
    - 'FOD_UPLOADER_OPTS=-ep 2 -pp 0 -I 1 -apf' 
    - 'FOD_NOTES=Triggered by GCP Pipeline'     
timeout: 2400s