# Integrate Fortify on Demand Static AppSec Testing (SAST) into your Google Cloud Build pipeline
# The following Google Cloud Build Secrets must be defined before using this job
#   - $$FOD_RELEASE_ID
#   - $$FOD_USER
#   - $$FOD_PAT
#   - $$FOD_TENANT

- name: 'fortifydocker/fortify-ci-tools:latest'
  entrypoint: bash
  args: 
    - -c
    - |
       scancentral package -oss -o package.zip
       FoDUpload -z package.zip -aurl $$FOD_API_URL -purl $$FOD_URL -rid $$FOD_RELEASE_ID -tc $$FOD_TENANT -uc $$FOD_USER $$FOD_PAT $$FOD_UPLOADER_OPTS -n "$$FOD_NOTES"
  secretEnv: ['FOD_RELEASE_ID', 'FOD_USER', 'FOD_PAT', 'FOD_TENANT'] 
  env:
    - 'FOD_URL=https://ams.fortify.com' 
    - 'FOD_API_URL=https://api.ams.fortify.com' 
    - 'FOD_UPLOADER_OPTS=-ep 2 -pp 0 -I 1 -apf' 
    - 'FOD_NOTES=Triggered by GCP Pipeline' 
  id: 'fortify-static-scan'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/fod_release_id/versions/latest
    env: 'FOD_RELEASE_ID'
  - versionName: projects/$PROJECT_ID/secrets/fod_user/versions/latest
    env: 'FOD_USER'
  - versionName: projects/$PROJECT_ID/secrets/fod_pat/versions/latest
    env: 'FOD_PAT' 
  - versionName: projects/$PROJECT_ID/secrets/fod_tenant/versions/latest
    env: 'FOD_TENANT' 
