# Integrate Fortify ScanCentral Static AppSec Testing (SAST) into your Google Cloud Build pipeline
# The following Google Cloud Build Secrets must be defined before using this step
#   - $$FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN
#   - $$FCLI_DEFAULT_SSC_USER
#   - $$FCLI_DEFAULT_SSC_PASSWORD
#   - $$FCLI_DEFAULT_SSC_CI_TOKEN
#   - $$FCLI_DEFAULT_SSC_URL
#   - $$SSC_APP_VERSION_ID


steps:
# SAST SCAN USING Fortify ScanCentral
- name: 'fortifydocker/fortify-ci-tools:5.4.1-jdk-17'
  entrypoint: bash
  args: 
    - -c
    - |
       echo Setting connection with Fortify Platform
       fcli ssc session login
       fcli sc-sast session login
          
       scancentral package -o package.zip --build-tool none --python-requirements requirements.txt
       fcli sc-sast scan start --publish-to=$$SSC_APP_VERSION_ID --sensor-version=$$SC_SAST_SENSOR_VERSION --package-file=package.zip --store=Id
       
       fcli sc-sast scan wait-for ::Id:: --interval=30s
       fcli ssc issue count --appversion=$$SSC_APP_VERSION_ID

       echo Terminating connection with Fortify Platform
       fcli sc-sast session logout
       fcli ssc session logout  

  secretEnv: ['FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN', 'FCLI_DEFAULT_SSC_USER', 'FCLI_DEFAULT_SSC_PASSWORD', 'FCLI_DEFAULT_SSC_CI_TOKEN', 'FCLI_DEFAULT_SSC_URL'] 
  env:
    - 'SSC_APP_VERSION_ID=${_SSC_APP_VERSION_ID}'
    - 'SC_SAST_SENSOR_VERSION=24.2'
  id: 'fortify-static-scan'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/fcli_default_sc_sast_client_auth_token/versions/latest
    env: 'FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/fcli_default_ssc_user/versions/latest
    env: 'FCLI_DEFAULT_SSC_USER'
  - versionName: projects/$PROJECT_ID/secrets/fcli_default_ssc_password/versions/latest
    env: 'FCLI_DEFAULT_SSC_PASSWORD' 
  - versionName: projects/$PROJECT_ID/secrets/fcli_default_ssc_ci_token/versions/latest
    env: 'FCLI_DEFAULT_SSC_CI_TOKEN'
  - versionName: projects/$PROJECT_ID/secrets/fcli_default_ssc_url/versions/latest
    env: 'FCLI_DEFAULT_SSC_URL'    
