version: 0.2
env:
  parameter-store:
      ###############################################################
      #          INTEGRATE FORTIFY ON DEMAND                        #
        FOD_RELEASE_ID_LOCAL: "/fod/releaseid"
        FCLI_DEFAULT_FOD_TENANT_LOCAL: "/fod/tenant"
        FCLI_DEFAULT_FOD_URL_LOCAL: "/fod/url"
        FCLI_DEFAULT_FOD_CLIENT_ID_LOCAL: "/fod/client_id"
        FCLI_DEFAULT_FOD_CLIENT_SECRET_LOCAL: "/fod/client_secret" 
      ###############################################################
      #           INTEGRATE FORTIFY SCANCENTRAL                     #
        FCLI_DEFAULT_SC_SAST_CLIENT_AUTH_TOKEN: "/fortify/client_auth_token"
        FCLI_DEFAULT_SSC_USER: "/fortify/ssc_user"
        FCLI_DEFAULT_SSC_PASSWORD: "/fortify/ssc_password"
        FCLI_DEFAULT_SSC_CI_TOKEN: "/fortify/ci_token"
        FCLI_DEFAULT_SSC_URL: "/fortify/ssc_url"
        SSC_APP_VERSION_ID: "/fortify/ssc_app_versionid"
phases:
  install:
    runtime-versions:
      java: corretto11corretto17
    commands:
      # Upgrade AWS CLI to the latest version
      #- pip install --upgrade awscli
  pre_build:
    commands:
      #- mvn clean compile test
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      ###################################################
      #             INTEGRATE FORTIFY SAST              #
      #                                                 #
      # For FORTIFY ON DEMAND uncomment the next line   #
      - bash fortify_sast_fod_template.bash
      #                                                 #
      # For FORTIFY SCANCENTRAL uncomment the next line #
      #- bash fortify_sast_scancentral_template.bash
      #                                                 #
      # For LOCAL FORTIFY SCA uncomment the next line   #
      #- bash fortify_sast_local_template.bash
      #                                                 #
      ###################################################
artifacts:
  files:
    - 'target/*.war'
